// import 'package:get/get.dart';
//
// class LocaleString extends Translations {
//   @override
//   Map<String, Map<String, String>> get keys => {
//     // English
//     'en_US': {
//       'hello': 'Hello World',
//       'message': 'Welcome to Newsflash',
//       'title': 'Flutter Language - Localization',
//       'subscribe': 'Subscribe Now',
//       'changelang': 'Change Language',
//       'settings': 'Settings',
//       'darkmode': 'Dark Mode',
//       'news': 'News',
//       'sample_article_1': 'Sample Article 1',
//       'sample_article_2': 'Sample Article 2',
//       'sample_content_1': 'This is the content of Sample Article 1.',
//       'sample_content_2': 'This is the content of Sample Article 2.',
//     },
//     // Spanish
//     'es_ES': {
//       'hello': 'Hola Mundo',
//       'message': 'Bienvenido a Newsflash',
//       'title': 'Lenguaje Flutter - Localización',
//       'subscribe': 'Suscríbete Ahora',
//       'changelang': 'Cambiar Idioma',
//       'settings': 'Configuraciones',
//       'darkmode': 'Modo Oscuro',
//       'news': 'Noticias',
//       'sample_article_1': 'Artículo de Muestra 1',
//       'sample_article_2': 'Artículo de Muestra 2',
//       'sample_content_1': 'Este es el contenido del Artículo de Muestra 1.',
//       'sample_content_2': 'Este es el contenido del Artículo de Muestra 2.',
//     },
//   };
// }
import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'hello': 'Hello World',
      'message': 'Welcome to Newsflash',
      'title': 'News Flash',
      'subscribe': 'Subscribe Now',
      'settings': 'Settings',
      'darkmode': 'DarkMode',
      'news':'News',
      'changelang': 'Change Language',
      'sample_article_1': 'As real as it gets',
      'sample_content_1': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_2': 'Economics rules – not OK',
      'sample_content_2': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_3': 'As real as it gets',
      'sample_content_3': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_4': 'Economics rules – not OK',
      'sample_content_4': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_5': 'As real as it gets',
      'sample_content_5': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_6': 'Economics rules – not OK',
      'sample_content_6': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_7': 'As real as it gets',
      'sample_content_7': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_8': 'Economics rules – not OK',
      'sample_content_8': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_9': 'As real as it gets',
      'sample_content_9': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_10': 'Economics rules – not OK',
      'sample_content_10': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_11': 'As real as it gets',
      'sample_content_11': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_12': 'Economics rules – not OK',
      'sample_content_12': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_13': 'As real as it gets',
      'sample_content_13': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_14': 'Economics rules – not OK',
      'sample_content_14': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_15': 'As real as it gets',
      'sample_content_15': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_16': 'Economics rules – not OK',
      'sample_content_16': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_17': 'As real as it gets',
      'sample_content_17': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_18': 'Economics rules – not OK',
      'sample_content_18': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_19': 'As real as it gets',
      'sample_content_19': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_20': 'Economics rules – not OK',
      'sample_content_20': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_21': 'As real as it gets',
      'sample_content_21': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_22': 'Economics rules – not OK',
      'sample_content_22': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_23': 'As real as it gets',
      'sample_content_23': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_24': 'Economics rules – not OK',
      'sample_content_24': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_25': 'As real as it gets',
      'sample_content_25': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_26': 'Economics rules – not OK',
      'sample_content_26': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_27': 'As real as it gets',
      'sample_content_27': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_28': 'Economics rules – not OK',
      'sample_content_28': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_29': 'As real as it gets',
      'sample_content_29': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_30': 'Economics rules – not OK',
      'sample_content_31': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
      'sample_article_32': 'As real as it gets',
      'sample_content_33': 'Debates on climate change are often dominated by heated commentary from the West on its impending peril calling it the biggest threat humanity has ever faced. But here in Bangladesh, climate change is not a threat – it is an ongoing reality.  In our reality, it is a slow compounding of already familiar struggles.',
      'sample_article_34': 'Economics rules – not OK',
      'sample_content_35': 'Economic decisions are made without the full understanding of the people they affect most. Katy Wiese spells out the issues. For many, economics is technical, jargon-laden, yet abstract, making it',
    },
    'es_ES': {
      'hello': 'Hola Mundo',
      'message': 'Bienvenido a Newsflash',
      'title': 'Noticia de última hora',
      'subscribe': 'Suscríbete Ahora',
      'settings': 'Ajustes',
      'darkmode': 'Modo oscuro',
      'news':'Noticias',
      'changelang': 'Cambiar Idioma',
      'sample_article_1': 'Tan real como parece',
      'sample_content_1': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_2': 'Reglas económicas: no están bien',
      'sample_content_2': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_3': 'Tan real como parece',
      'sample_content_3': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_4': 'Reglas económicas: no están bien',
      'sample_content_4': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_5': 'Tan real como parece',
      'sample_content_5': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_6': 'Reglas económicas: no están bien',
      'sample_content_6': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_7': 'Tan real como parece',
      'sample_content_7': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_8': 'Reglas económicas: no están bien',
      'sample_content_8': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_9': 'Tan real como parece',
      'sample_content_9': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_10': 'Reglas económicas: no están bien',
      'sample_content_10': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_11': 'Tan real como parece',
      'sample_content_11': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_12': 'Reglas económicas: no están bien',
      'sample_content_12': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_13': 'Tan real como parece',
      'sample_content_13': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_14': 'Reglas económicas: no están bien',
      'sample_content_14': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_15': 'Tan real como parece',
      'sample_content_15': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_16': 'Reglas económicas: no están bien',
      'sample_content_16': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_17': 'Tan real como parece',
      'sample_content_17': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_18': 'Reglas económicas: no están bien',
      'sample_content_18': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_19': 'Tan real como parece',
      'sample_content_19': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_20': 'Reglas económicas: no están bien',
      'sample_content_20': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_21': 'Tan real como parece',
      'sample_content_21': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_22': 'Reglas económicas: no están bien',
      'sample_content_22': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_23': 'Tan real como parece',
      'sample_content_23': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_24': 'Reglas económicas: no están bien',
      'sample_content_24': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_25': 'Tan real como parece',
      'sample_content_25': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_26': 'Reglas económicas: no están bien',
      'sample_content_26': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_27': 'Tan real como parece',
      'sample_content_27': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_28': 'Reglas económicas: no están bien',
      'sample_content_28': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_29': 'Tan real como parece',
      'sample_content_29': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_30': 'Reglas económicas: no están bien',
      'sample_content_30': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_31': 'Tan real como parece',
      'sample_content_31': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_32': 'Reglas económicas: no están bien',
      'sample_content_32': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_33': 'Tan real como parece',
      'sample_content_33': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',
      'sample_article_34': 'Reglas económicas: no están bien',
      'sample_content_34': 'Las decisiones económicas se toman sin la plena comprensión de las personas a las que más afectan. Katy Wiese explica detalladamente los problemas. Para muchos, la economía es técnica, está cargada de jerga, pero es abstracta, lo que la hace',
      'sample_article_35': 'Tan real como parece',
      'sample_content_35': 'Los debates sobre el cambio climático a menudo están dominados por acalorados comentarios de Occidente sobre su peligro inminente, calificándolo de la mayor amenaza que jamás haya enfrentado la humanidad. Pero aquí en Bangladesh, el cambio climático no es una amenaza: es una realidad constante.  En nuestra realidad, se trata de una lenta agravación de luchas ya familiares.Los peores impactos del cambio climático, en forma de estrés por calor, aumento de la salinidad y lluvias irregulares, se desarrollan dentro de luchas familiares. Incluyen llamados a salarios y condiciones de trabajo justos. Las mejoras necesarias en el entorno de trabajo incluyen una mayor necesidad de pausas para tomar agua y refrigeración, especialmente para quienes trabajan al aire libre o en áreas cerradas para cocinar. Estas necesidades ahora se han intensificado en un clima más cálido.',

    },
  };
}
